2024-08-09 03:06:21,679 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.2:38636'
2024-08-09 03:06:22,913 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.2:40304
2024-08-09 03:06:22,913 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.2:40304
2024-08-09 03:06:22,913 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 03:06:22,913 - distributed.worker - INFO -          dashboard at:           10.34.59.2:36006
2024-08-09 03:06:22,913 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:40758
2024-08-09 03:06:22,913 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 03:06:22,913 - distributed.worker - INFO -               Threads:                          1
2024-08-09 03:06:22,913 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 03:06:22,913 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-hdlcdfd8
2024-08-09 03:06:22,913 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 03:06:23,467 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 03:06:23,467 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:40758
2024-08-09 03:06:23,467 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 03:06:23,468 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:40758
slurmstepd: error: *** JOB 2328408 ON cl-node002 CANCELLED AT 2024-08-09T03:06:45 ***
2024-08-09 03:06:45,131 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.2:40304. Reason: scheduler-close
2024-08-09 03:06:45,132 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:51772 remote=tcp://10.34.59.1:40758>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:51772 remote=tcp://10.34.59.1:40758>: Stream is closed
2024-08-09 03:06:45,136 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.2:38636'. Reason: scheduler-close
2024-08-09 03:06:45,138 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:40758; closing.
2024-08-09 03:06:45,139 - distributed.nanny - INFO - Worker closed
