2024-08-09 08:22:02,624 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.18:34404'
2024-08-09 08:22:03,691 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.18:41608
2024-08-09 08:22:03,691 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.18:41608
2024-08-09 08:22:03,692 - distributed.worker - INFO -           Worker name:            SLURMCluster-13
2024-08-09 08:22:03,692 - distributed.worker - INFO -          dashboard at:          10.34.59.18:33041
2024-08-09 08:22:03,692 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:39844
2024-08-09 08:22:03,692 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:22:03,692 - distributed.worker - INFO -               Threads:                          1
2024-08-09 08:22:03,692 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 08:22:03,692 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-cemhixgz
2024-08-09 08:22:03,692 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:22:04,049 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 08:22:04,050 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:39844
2024-08-09 08:22:04,050 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:22:04,050 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:39844
slurmstepd: error: *** JOB 2331540 ON cl-node018 CANCELLED AT 2024-08-09T08:22:23 ***
2024-08-09 08:22:23,070 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.18:41608. Reason: scheduler-close
2024-08-09 08:22:23,071 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.18:59106 remote=tcp://10.34.59.1:39844>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.18:59106 remote=tcp://10.34.59.1:39844>: Stream is closed
2024-08-09 08:22:23,073 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.18:34404'. Reason: scheduler-close
2024-08-09 08:22:23,075 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:39844; closing.
2024-08-09 08:22:23,075 - distributed.nanny - INFO - Worker closed
