2024-08-09 04:24:17,726 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:36087'
2024-08-09 04:24:18,878 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:44583
2024-08-09 04:24:18,878 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:44583
2024-08-09 04:24:18,878 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2024-08-09 04:24:18,878 - distributed.worker - INFO -          dashboard at:          10.34.59.10:45204
2024-08-09 04:24:18,878 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:35574
2024-08-09 04:24:18,878 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:24:18,878 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:24:18,878 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:24:18,878 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-d6p2vkqx
2024-08-09 04:24:18,878 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:24:19,325 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:24:19,326 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:35574
2024-08-09 04:24:19,326 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:24:19,326 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:35574
slurmstepd: error: *** JOB 2328999 ON cl-node010 CANCELLED AT 2024-08-09T04:24:28 ***
2024-08-09 04:24:28,103 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:44583. Reason: scheduler-close
2024-08-09 04:24:28,104 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:40132 remote=tcp://10.34.59.1:35574>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:40132 remote=tcp://10.34.59.1:35574>: Stream is closed
2024-08-09 04:24:28,109 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.10:36087'. Reason: scheduler-close
2024-08-09 04:24:28,112 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:35574; closing.
2024-08-09 04:24:28,112 - distributed.nanny - INFO - Worker closed
