2024-08-09 04:04:07,638 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.20:35520'
2024-08-09 04:04:08,231 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-n8nf_yhb', purging
2024-08-09 04:04:08,862 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.20:37128
2024-08-09 04:04:08,862 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.20:37128
2024-08-09 04:04:08,862 - distributed.worker - INFO -           Worker name:             SLURMCluster-1
2024-08-09 04:04:08,862 - distributed.worker - INFO -          dashboard at:          10.34.59.20:38247
2024-08-09 04:04:08,862 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:44058
2024-08-09 04:04:08,862 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:04:08,863 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:04:08,863 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:04:08,863 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-amr_5lg2
2024-08-09 04:04:08,863 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:04:09,423 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:04:09,424 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:44058
2024-08-09 04:04:09,424 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:04:09,424 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:44058
slurmstepd: error: *** JOB 2328835 ON cl-node020 CANCELLED AT 2024-08-09T04:04:23 ***
2024-08-09 04:04:23,437 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.20:37128. Reason: scheduler-close
2024-08-09 04:04:23,438 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.20:59436 remote=tcp://10.34.59.1:44058>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.20:59436 remote=tcp://10.34.59.1:44058>: Stream is closed
2024-08-09 04:04:23,442 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.20:35520'. Reason: scheduler-close
2024-08-09 04:04:23,444 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:44058; closing.
2024-08-09 04:04:23,444 - distributed.nanny - INFO - Worker closed
