2024-08-09 08:23:07,678 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.18:40473'
2024-08-09 08:23:08,745 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.18:42703
2024-08-09 08:23:08,745 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.18:42703
2024-08-09 08:23:08,745 - distributed.worker - INFO -           Worker name:            SLURMCluster-13
2024-08-09 08:23:08,745 - distributed.worker - INFO -          dashboard at:          10.34.59.18:44994
2024-08-09 08:23:08,745 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:43916
2024-08-09 08:23:08,745 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:23:08,745 - distributed.worker - INFO -               Threads:                          1
2024-08-09 08:23:08,745 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 08:23:08,745 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-smfiwk2u
2024-08-09 08:23:08,745 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:23:09,100 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 08:23:09,101 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:43916
2024-08-09 08:23:09,101 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:23:09,102 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:43916
slurmstepd: error: *** JOB 2331572 ON cl-node018 CANCELLED AT 2024-08-09T08:23:27 ***
2024-08-09 08:23:27,998 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.18:42703. Reason: scheduler-close
2024-08-09 08:23:27,999 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.18:38952 remote=tcp://10.34.59.1:43916>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.18:38952 remote=tcp://10.34.59.1:43916>: Stream is closed
2024-08-09 08:23:28,002 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.18:40473'. Reason: scheduler-close
2024-08-09 08:23:28,005 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:43916; closing.
2024-08-09 08:23:28,005 - distributed.nanny - INFO - Worker closed
