2024-08-09 04:06:06,943 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.20:34304'
2024-08-09 04:06:08,046 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.20:42795
2024-08-09 04:06:08,046 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.20:42795
2024-08-09 04:06:08,046 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 04:06:08,047 - distributed.worker - INFO -          dashboard at:          10.34.59.20:39738
2024-08-09 04:06:08,047 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:45260
2024-08-09 04:06:08,047 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:06:08,047 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:06:08,047 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:06:08,047 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-3i4w5ezd
2024-08-09 04:06:08,047 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:06:08,405 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:06:08,406 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:45260
2024-08-09 04:06:08,406 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:06:08,406 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:45260
slurmstepd: error: *** JOB 2328843 ON cl-node020 CANCELLED AT 2024-08-09T04:06:23 ***
2024-08-09 04:06:23,638 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.20:42795. Reason: scheduler-close
2024-08-09 04:06:23,639 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.20:56184 remote=tcp://10.34.59.1:45260>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.20:56184 remote=tcp://10.34.59.1:45260>: Stream is closed
2024-08-09 04:06:23,641 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.20:34304'. Reason: scheduler-close
2024-08-09 04:06:23,644 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:45260; closing.
2024-08-09 04:06:23,644 - distributed.nanny - INFO - Worker closed
