2024-08-09 07:58:00,279 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.5:45957'
2024-08-09 07:58:00,283 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.5:36448'
2024-08-09 07:58:00,875 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-mhv4o3uw', purging
2024-08-09 07:58:01,390 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.5:38817
2024-08-09 07:58:01,390 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.5:38817
2024-08-09 07:58:01,390 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-0
2024-08-09 07:58:01,390 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.5:35029
2024-08-09 07:58:01,390 - distributed.worker - INFO -          dashboard at:           10.34.59.5:34939
2024-08-09 07:58:01,390 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.5:35029
2024-08-09 07:58:01,390 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:36925
2024-08-09 07:58:01,390 - distributed.worker - INFO -           Worker name:           SLURMCluster-0-1
2024-08-09 07:58:01,390 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:58:01,390 - distributed.worker - INFO -               Threads:                          1
2024-08-09 07:58:01,390 - distributed.worker - INFO -          dashboard at:           10.34.59.5:45524
2024-08-09 07:58:01,390 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 07:58:01,390 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:36925
2024-08-09 07:58:01,390 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-07kqnawi
2024-08-09 07:58:01,390 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:58:01,390 - distributed.worker - INFO -               Threads:                          1
2024-08-09 07:58:01,390 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:58:01,390 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 07:58:01,390 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-6dxbduah
2024-08-09 07:58:01,390 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:58:01,792 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 07:58:01,792 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 07:58:01,792 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:36925
2024-08-09 07:58:01,793 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:58:01,793 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:36925
2024-08-09 07:58:01,793 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:36925
2024-08-09 07:58:01,793 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:58:01,793 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:36925
slurmstepd: error: *** JOB 2331231 ON cl-node005 CANCELLED AT 2024-08-09T07:58:37 ***
2024-08-09 07:58:37,791 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.5:38817. Reason: scheduler-close
2024-08-09 07:58:37,791 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.5:35029. Reason: scheduler-close
2024-08-09 07:58:37,792 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:48680 remote=tcp://10.34.59.1:36925>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:48680 remote=tcp://10.34.59.1:36925>: Stream is closed
2024-08-09 07:58:37,793 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:48682 remote=tcp://10.34.59.1:36925>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.5:48682 remote=tcp://10.34.59.1:36925>: Stream is closed
2024-08-09 07:58:37,797 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/worker.py", line 1252, in heartbeat
    response = await retry_operation(
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/utils_comm.py", line 452, in retry_operation
    return await retry(
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/utils_comm.py", line 431, in retry
    return await coro()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/core.py", line 1395, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/core.py", line 1154, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.34.59.5:48684 remote=tcp://10.34.59.1:36925>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-08-09 07:58:37,798 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.5:45957'. Reason: scheduler-close
2024-08-09 07:58:37,797 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/worker.py", line 1252, in heartbeat
    response = await retry_operation(
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/utils_comm.py", line 452, in retry_operation
    return await retry(
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/utils_comm.py", line 431, in retry
    return await coro()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/core.py", line 1395, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/core.py", line 1154, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.34.59.5:48686 remote=tcp://10.34.59.1:36925>: ConnectionResetError: [Errno 104] Connection reset by peer
2024-08-09 07:58:37,799 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.5:36448'. Reason: scheduler-close
2024-08-09 07:58:37,800 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:36925; closing.
2024-08-09 07:58:37,800 - distributed.nanny - INFO - Worker closed
2024-08-09 07:58:37,802 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:36925; closing.
2024-08-09 07:58:37,802 - distributed.nanny - INFO - Worker closed
