2024-08-09 04:05:06,659 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.2:45212'
2024-08-09 04:05:07,286 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-o01os92x', purging
2024-08-09 04:05:07,758 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.2:33215
2024-08-09 04:05:07,758 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.2:33215
2024-08-09 04:05:07,758 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 04:05:07,758 - distributed.worker - INFO -          dashboard at:           10.34.59.2:46622
2024-08-09 04:05:07,758 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:41035
2024-08-09 04:05:07,758 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:05:07,759 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:05:07,759 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:05:07,759 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-nu5_so2g
2024-08-09 04:05:07,759 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:05:08,115 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:05:08,115 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:41035
2024-08-09 04:05:08,115 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:05:08,116 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:41035
slurmstepd: error: *** JOB 2328838 ON cl-node002 CANCELLED AT 2024-08-09T04:05:23 ***
2024-08-09 04:05:23,507 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.2:33215. Reason: scheduler-close
2024-08-09 04:05:23,508 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:50870 remote=tcp://10.34.59.1:41035>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:50870 remote=tcp://10.34.59.1:41035>: Stream is closed
