2024-08-09 06:29:54,659 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.8:38401'
2024-08-09 06:29:55,730 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.8:36561
2024-08-09 06:29:55,730 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.8:36561
2024-08-09 06:29:55,730 - distributed.worker - INFO -           Worker name:             SLURMCluster-5
2024-08-09 06:29:55,730 - distributed.worker - INFO -          dashboard at:           10.34.59.8:37196
2024-08-09 06:29:55,731 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:46714
2024-08-09 06:29:55,731 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:55,731 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:29:55,731 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:29:55,731 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-tbcgrrip
2024-08-09 06:29:55,731 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:56,088 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:29:56,088 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:46714
2024-08-09 06:29:56,089 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:56,089 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:46714
slurmstepd: error: *** JOB 2330563 ON cl-node008 CANCELLED AT 2024-08-09T06:30:14 ***
2024-08-09 06:30:14,688 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.8:36561. Reason: scheduler-close
2024-08-09 06:30:14,689 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.8:55344 remote=tcp://10.34.59.1:46714>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.8:55344 remote=tcp://10.34.59.1:46714>: Stream is closed
2024-08-09 06:30:14,691 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.8:38401'. Reason: scheduler-close
