2024-08-09 05:37:50,575 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.2:32931'
2024-08-09 05:37:51,831 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.2:38466
2024-08-09 05:37:51,831 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.2:38466
2024-08-09 05:37:51,831 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 05:37:51,831 - distributed.worker - INFO -          dashboard at:           10.34.59.2:36385
2024-08-09 05:37:51,831 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:36873
2024-08-09 05:37:51,831 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 05:37:51,831 - distributed.worker - INFO -               Threads:                          1
2024-08-09 05:37:51,831 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 05:37:51,831 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-s6vgd_i1
2024-08-09 05:37:51,831 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 05:37:52,370 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 05:37:52,370 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:36873
2024-08-09 05:37:52,370 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 05:37:52,371 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:36873
slurmstepd: error: *** JOB 2330361 ON cl-node002 CANCELLED AT 2024-08-09T05:39:31 ***
2024-08-09 05:39:31,013 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.2:38466. Reason: scheduler-close
2024-08-09 05:39:31,015 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:55796 remote=tcp://10.34.59.1:36873>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:55796 remote=tcp://10.34.59.1:36873>: Stream is closed
2024-08-09 05:39:31,021 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.2:32931'. Reason: scheduler-close
2024-08-09 05:39:31,024 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:36873; closing.
2024-08-09 05:39:31,024 - distributed.nanny - INFO - Worker closed
