2024-08-09 06:17:18,176 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:41319'
2024-08-09 06:17:19,298 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:44231
2024-08-09 06:17:19,298 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:44231
2024-08-09 06:17:19,298 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2024-08-09 06:17:19,298 - distributed.worker - INFO -          dashboard at:           10.34.59.6:37965
2024-08-09 06:17:19,298 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:43598
2024-08-09 06:17:19,298 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:17:19,298 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:17:19,299 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:17:19,299 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-lhojtj72
2024-08-09 06:17:19,299 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:17:19,706 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:17:19,706 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:43598
2024-08-09 06:17:19,706 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:17:19,707 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:43598
2024-08-09 06:17:56,104 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:44231. Reason: scheduler-close
2024-08-09 06:17:56,105 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:42264 remote=tcp://10.34.59.1:43598>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:42264 remote=tcp://10.34.59.1:43598>: Stream is closed
2024-08-09 06:17:56,108 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:41319'. Reason: scheduler-close
2024-08-09 06:17:56,110 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:43598; closing.
2024-08-09 06:17:56,110 - distributed.nanny - INFO - Worker closed
slurmstepd: error: *** JOB 2330445 ON cl-node006 CANCELLED AT 2024-08-09T06:17:56 ***
