2024-08-09 06:29:54,687 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:45850'
2024-08-09 06:29:55,283 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-kte69f6b', purging
2024-08-09 06:29:55,761 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:39345
2024-08-09 06:29:55,761 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:39345
2024-08-09 06:29:55,761 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2024-08-09 06:29:55,761 - distributed.worker - INFO -          dashboard at:          10.34.59.10:35072
2024-08-09 06:29:55,761 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:46714
2024-08-09 06:29:55,761 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:55,761 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:29:55,761 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:29:55,761 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-63ge8js4
2024-08-09 06:29:55,761 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:56,122 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:29:56,123 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:46714
2024-08-09 06:29:56,123 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:29:56,124 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:46714
slurmstepd: error: *** JOB 2330565 ON cl-node010 CANCELLED AT 2024-08-09T06:30:14 ***
2024-08-09 06:30:14,688 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:39345. Reason: scheduler-close
2024-08-09 06:30:14,689 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:55560 remote=tcp://10.34.59.1:46714>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:55560 remote=tcp://10.34.59.1:46714>: Stream is closed
